import "./globals.css";
import { Montserrat } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={`${montserrat.variable} scroll-smooth`} lang="pt-br">
      <head>
        <title>Scientific Liguagem - Precisamente o que você quer dizer</title>
      </head>
      <body className="font-montserrat" >{children}</body>
    </html>
  );
}
